//! Regression coverage for AC #3 + AC #4 (issue #5):
//!
//! `POST /api/sessions/complete` must create **exactly one** fallback
//! `session_summaries` row when the session was never explicitly
//! summarized, and that row must be findable via:
//!
//! 1. SQLite FTS5 directly against `session_summaries_fts` (proves the
//!    insert trigger fired and the row is indexed).
//! 2. The worker's HTTP search endpoint
//!    (`/api/search?query=...&type=sessions`) — proves the searchable
//!    representation matches the indexed shape.
//!
//! The MCP-side recall path is covered by a sibling test in
//! `crates/claude-mem-mcp/tests/fallback_summary_mcp_search.rs` to keep
//! the worker crate's test dependencies tight.

use axum::body::{to_bytes, Body};
use axum::http::{Method, Request, StatusCode};
use claude_mem_core::db::sessions::{create_session, update_memory_session_id};
use claude_mem_core::types::session::CreateSessionInput;
use claude_mem_worker::http::router::{build_router_with_state, AppState};
use serde_json::{json, Value};
use tower::ServiceExt;

const FALLBACK_NOTE: &str = "Generated by claude-mem-rs session summary fallback.";

async fn post_json(app: axum::Router, uri: &str, body: Value) -> (StatusCode, Value) {
    let response = app
        .oneshot(
            Request::builder()
                .method(Method::POST)
                .uri(uri)
                .header("content-type", "application/json")
                .body(Body::from(body.to_string()))
                .unwrap(),
        )
        .await
        .unwrap();
    let status = response.status();
    let body = to_bytes(response.into_body(), usize::MAX).await.unwrap();
    let value = serde_json::from_slice(&body).unwrap_or_default();
    (status, value)
}

async fn get_json(app: axum::Router, uri: &str) -> (StatusCode, Value) {
    let response = app
        .oneshot(
            Request::builder()
                .method(Method::GET)
                .uri(uri)
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    let status = response.status();
    let body = to_bytes(response.into_body(), usize::MAX).await.unwrap();
    (status, serde_json::from_slice(&body).unwrap())
}

/// Seeds a session that already has a `memory_session_id` so that
/// `sessions_complete` will trigger the fallback summary path
/// (`memory_session_id.is_some()` branch in `routes::sessions_complete`).
fn seed_session_with_memory(state: &AppState, content: &str, memory: &str, project: &str) {
    let conn = state.conn.lock().unwrap();
    create_session(
        &conn,
        &CreateSessionInput {
            content_session_id: content.into(),
            project: project.into(),
            user_prompt: Some(format!("Seed prompt for {content}")),
            started_at: "2024-06-01T09:00:00.000Z".into(),
            started_at_epoch: 1_717_232_400_000,
        },
    )
    .unwrap();
    update_memory_session_id(&conn, content, memory).unwrap();
}

fn count_summaries(state: &AppState, memory_session_id: &str) -> i64 {
    let conn = state.conn.lock().unwrap();
    conn.query_row(
        "SELECT COUNT(*) FROM session_summaries WHERE memory_session_id = ?1",
        [memory_session_id],
        |row| row.get(0),
    )
    .unwrap()
}

fn fts_match_count(state: &AppState, fts_query: &str) -> i64 {
    let conn = state.conn.lock().unwrap();
    conn.query_row(
        "SELECT COUNT(*) FROM session_summaries_fts WHERE session_summaries_fts MATCH ?1",
        [fts_query],
        |row| row.get(0),
    )
    .unwrap()
}

#[tokio::test]
async fn sessions_complete_without_summary_creates_exactly_one_fallback_summary() {
    let state = AppState::in_memory().unwrap();
    seed_session_with_memory(
        &state,
        "fallback-content-1",
        "fallback-memory-1",
        "cloudy-fork",
    );
    let app = build_router_with_state(state.clone());

    assert_eq!(
        count_summaries(&state, "fallback-memory-1"),
        0,
        "precondition: no summary should exist before /api/sessions/complete"
    );

    let (status, body) = post_json(
        app.clone(),
        "/api/sessions/complete",
        json!({
            "contentSessionId": "fallback-content-1",
            "platformSource": "claude"
        }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body["completed"], true);
    assert!(
        body["summaryId"].as_i64().unwrap() > 0,
        "session_complete must return a non-null summaryId for the new fallback row, got {body}"
    );

    let row_count = count_summaries(&state, "fallback-memory-1");
    assert_eq!(
        row_count, 1,
        "fallback path must create exactly one summary row, found {row_count}"
    );
}

#[tokio::test]
async fn fallback_summary_is_recoverable_via_sqlite_fts5_directly() {
    let state = AppState::in_memory().unwrap();
    seed_session_with_memory(
        &state,
        "fallback-fts-1",
        "fallback-fts-memory",
        "cloudy-fork",
    );
    let app = build_router_with_state(state.clone());

    // No explicit summary → triggers fallback.
    let (status, _) = post_json(
        app.clone(),
        "/api/sessions/complete",
        json!({ "contentSessionId": "fallback-fts-1" }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    // The fallback writes a known sentinel into `notes` ("Generated by
    // claude-mem-rs session summary fallback.") — pin the FTS5 path on
    // that. `session_summaries_fts` indexes `notes` per migration 26.
    let hits = fts_match_count(&state, "fallback");
    assert!(
        hits >= 1,
        "session_summaries_fts must surface the fallback summary on `fallback` query, got {hits}"
    );

    // Also assert the canonical sentinel survives strop/round-trip into
    // the indexed `notes` column.
    let conn = state.conn.lock().unwrap();
    let notes: String = conn
        .query_row(
            "SELECT notes FROM session_summaries WHERE memory_session_id = ?1",
            ["fallback-fts-memory"],
            |row| row.get(0),
        )
        .unwrap();
    assert_eq!(notes, FALLBACK_NOTE);
}

#[tokio::test]
async fn fallback_summary_is_recoverable_via_worker_search_route() {
    let state = AppState::in_memory().unwrap();
    seed_session_with_memory(
        &state,
        "fallback-search-1",
        "fallback-search-memory",
        "cloudy-fork",
    );
    let app = build_router_with_state(state.clone());

    let (status, _) = post_json(
        app.clone(),
        "/api/sessions/complete",
        json!({ "contentSessionId": "fallback-search-1" }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    // The fallback summary's `request` is the original prompt
    // ("Seed prompt for fallback-search-1"). Search by a token from that
    // prompt and require the type=sessions result set returns the row.
    let (status, search) = get_json(
        app.clone(),
        "/api/search?query=Seed&project=cloudy-fork&type=sessions&limit=10",
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    let sessions = search["sessions"].as_array().unwrap();
    assert_eq!(
        sessions.len(),
        1,
        "expected exactly one session result, got {search}"
    );
    assert_eq!(
        sessions[0]["memory_session_id"], "fallback-search-memory",
        "session result must point at the fallback memory id"
    );

    // The session status endpoint must also see the fallback summary.
    let (status, session_status) = get_json(
        app,
        "/api/sessions/status?contentSessionId=fallback-search-1",
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(session_status["hasSummary"], true);
    assert_eq!(session_status["summaryCount"], 1);
}

#[tokio::test]
async fn sessions_complete_is_idempotent_and_does_not_duplicate_fallback_summary() {
    // Calling `/api/sessions/complete` twice (e.g. from a Stop hook
    // followed by a SessionEnd hook) must not create a second fallback
    // summary row — the handler explicitly checks
    // `get_summary_for_session(...).is_empty()` before inserting.
    let state = AppState::in_memory().unwrap();
    seed_session_with_memory(
        &state,
        "fallback-idem-1",
        "fallback-idem-memory",
        "cloudy-fork",
    );
    let app = build_router_with_state(state.clone());

    let (status, first) = post_json(
        app.clone(),
        "/api/sessions/complete",
        json!({ "contentSessionId": "fallback-idem-1" }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert!(first["summaryId"].as_i64().unwrap() > 0);

    let (status, second) = post_json(
        app.clone(),
        "/api/sessions/complete",
        json!({ "contentSessionId": "fallback-idem-1" }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(
        second["summaryId"],
        Value::Null,
        "second complete must not create a duplicate summary"
    );

    assert_eq!(
        count_summaries(&state, "fallback-idem-memory"),
        1,
        "idempotency guard must keep summary count at 1 across multiple complete calls"
    );
}

#[tokio::test]
async fn sessions_complete_without_memory_session_id_skips_fallback_summary() {
    // Pin a parity guard: if `memory_session_id` is still NULL (session
    // never reached the observer pipeline), `sessions_complete` must
    // skip the fallback insert. This prevents the fallback from clobbering
    // an "empty" session that's still mid-bootstrap.
    let state = AppState::in_memory().unwrap();
    {
        let conn = state.conn.lock().unwrap();
        create_session(
            &conn,
            &CreateSessionInput {
                content_session_id: "fallback-no-memory-1".into(),
                project: "cloudy-fork".into(),
                user_prompt: Some("No memory id seeded".into()),
                started_at: "2024-06-01T09:00:00.000Z".into(),
                started_at_epoch: 1_717_232_400_000,
            },
        )
        .unwrap();
    }
    let app = build_router_with_state(state.clone());

    let (status, body) = post_json(
        app,
        "/api/sessions/complete",
        json!({ "contentSessionId": "fallback-no-memory-1" }),
    )
    .await;
    assert_eq!(status, StatusCode::OK);
    assert_eq!(body["completed"], true);
    assert_eq!(
        body["summaryId"],
        Value::Null,
        "no fallback summary should be created when memory_session_id is NULL"
    );

    let conn = state.conn.lock().unwrap();
    let total: i64 = conn
        .query_row("SELECT COUNT(*) FROM session_summaries", [], |row| {
            row.get(0)
        })
        .unwrap();
    assert_eq!(
        total, 0,
        "session_summaries must remain empty when fallback is skipped"
    );
}
